version: '3'

services:
  app:
    build: .
    container_name: marleyspoon
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - CONTENTFUL_SPACE_ID
      - CONTENTFUL_ENVIRONMENT
      - CONTENTFUL_ACCESS_TOKEN
    ports:
      - "9898:9898"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
